config/routes.rb
ItmatArchive::Application.routes.draw do
    resources :experiments, only: [:index,:show] do
        member do
            get :record
        end
    end
    root to: redirect("/experiments")
end

app/models/experiment.rb
require "json"
class Experiment < ActiveRecord::Base
    serialize :owners, Array

    attr_accessible :qinteract_project_id, :project_name, :owners,
        :archive_disk, :achive_folder_name, :record_string

    def record
        @record ||= JSON.parse(record_string)
    end
    def record=(json_record)
        self.record_string = json_record.to_s()
    end

    include PgSearch
    pg_search_scope :search, against: [:project_name, :owners, :record_string],
        using: {
            tsearch: {
                dictionary: 'english',
                prefix: true,
                any_word: true,
                tsvector_column: 'tsv_record'
            }
        }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
    def index
        if params[:query]
            @query = params[:query]
            @experiments = Experiment.search(@query).page(params[:page] || 1)
        else
            @experiments = Experiment.page(params[:page] || 1)
        end
    end
    def show
        @experiment = Experiment.find(params[:id])
    end
    def record
        @experiment = Experiment.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/index.html.haml
%h2 Experiments
- if params[:query]
  %h4==Query = "#{params[:query]}" (#{link_to "clear search", root_path})
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th qInteract Project ID
      %th Project Name
      %th Owners
      %th Archive Disk
      %th Archive Folder
  %tbody
    - for experiment in @experiments
      %tr
        %td=link_to(experiment.qinteract_project_id, experiment_path(experiment))
        %td=link_to(experiment.project_name, experiment_path(experiment))
        %td=experiment.owners.join(", ")
        %td=experiment.archive_disk
        %td=experiment.archive_folder_name

=will_paginate(@experiments)

app/views/experiments/record.html.haml
%h2==Project: #{@experiment.project_name}
%pre
    =@experiment.record.to_yaml

app/views/experiments/show.html.haml
%h2==Project: #{@experiment.project_name}



%table.table.table-bordered
  %tbody
    %tr
      %th qInteract Project ID
      %td= @experiment.qinteract_project_id
    %tr
      %th Project Name
      %td= @experiment.project_name
    %tr
      %th Owners
      %td=@experiment.owners
    %tr
      %th Archive Disk
      %td= @experiment.archive_disk
    %tr
      %th Archive Folder
      %td= @experiment.archive_folder_name

=link_to "Show Full Record", record_experiment_path(), method: 'get', class: 'btn btn-large'
%h4 Analyses
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Name
      %th Owners
      %th Search Type
  %tbody
    -for analysis in @experiment.record['analyses']
      %tr
        %td=analysis["analysis_name"]
        %td=analysis["owner"]
        %td=analysis["search"]["algorithm"]
%h4 Files
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Path
      %th MD5 Sum
  %tbody
    -for f in @experiment.record['file_list']
      %tr
        %td=f["path"]
        %td=f["md5"]

app/views/layouts/application.html.haml
!!!
%head
  %title ITMAT Archive
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
.container
  .header.row
    =render partial: "shared/header"
  .content.row
    .span12= yield
  .footer.row
    .span12=render partial: 'shared/footer'
.js
  = yield :js

app/views/shared/_footer.html.haml
.text-center.span12= link_to "ITMAT", "http://www.itmat.upenn.edu"

app/views/shared/_header.html.haml
.span8
  .logoText
    %a{ href: root_path}
      =image_tag('icon.png')
      ITMAT Proteomics Archive
    |
    = link_to "About/Help", url_for("/about.html")
.span4.pull-right
  =form_tag experiments_path, method: 'get', class: 'navbar-search' do
    =text_field_tag :query, nil, class: 'search-query  span3', placeholder: "Search", value: params[:query] ? params[:query]: nil
    =submit_tag "Go"